### ISSUE TITLE
Error on installing required packages

### ISSUE THREAD

**Issue by matt-jay** [thedataincubator/ds30#1]
I am getting the following error when trying to install the components listed in requirements.txt:

```
HTTP error 406 while getting https://github.com/thedataincubator/onlineldavb.git@master
Could not install requirement https://github.com/thedataincubator/onlineldavb.git@master (from -r requirements.txt (line 5)) because of error 406 Client Error: Not Acceptable
Could not install requirement https://github.com/thedataincubator/onlineldavb.git@master (from -r requirements.txt (line 5)) because of HTTP error 406 Client Error: Not Acceptable for URL https://github.com/thedataincubator/onlineldavb.git@master
```

Can anyone tell me what might be going wrong?

(Observed with pip version 7.1.2 on MacOS 10.11)

**Comment by neil-s** [comment]
To add some detail, since I'm having the same issue:
There is an error whether using Python 2 or 3, on Windows or Linux. I tried changing to the SSH clone URL for that repository, and removing the "@master" part of the link, but nothing worked.

**Comment by patim** [comment]
Same error on Ubuntu 14.04

**Comment by SynbioLucas** [comment]
I fixed this problem by prepending `git+` to line 5:

```
git+https://github.com/thedataincubator/onlineldavb.git@master
```

[Via StackOverflow](http://stackoverflow.com/questions/20101834/pip-install-from-github-repo-branch)

**Comment by neil-s** [comment]
That worked, thanks!

**Comment by matt-jay** [comment]
Also works for me. This [thread on SO](http://stackoverflow.com/questions/31457753/what-does-git-mean-in-the-url) explains why.
