### ISSUE TITLE
Installing python packages

### ISSUE THREAD

**Issue by patim** [thedataincubator/ds30#5]
Does anybody have difficulty installing python packages? I get an error: Command python setup.py egg_info failed with error code 1

Working in Ubuntu 14.04

**Comment by tianhuil** [comment]
@patim: unfortunately, installing python packages can be a git of a pain and is highly system dependent.  At [The Data Incubator](https://www.thedataincubator.com/), we just give you a server with all the necessary packages installed.

**Comment by zelnet94** [comment]
@patim: make sure you are using python2 to setup, ds30 runs on python2 so if you're using python3, you may run into some weird errors.

**Comment by patim** [comment]
@zelmundo94: I have multiple versions of python installed, not sure which one is being used.

**Comment by tomverweij** [comment]
Hey Patim,

Same issue but on a Win7 machine with a freshly installed Python2.7. Last traceback line:
"python setup.py egg_info" failed with error code 1

I'm new to Python and glanced over the complete traceback. It seems to trip on the scipy package not being able to find libraries.

Did you finally succeed getting it going? Assuming this is part of the learning process, I'll keep looking :-)

**Comment by patim** [comment]
@tomverweij, I made it through some errors, but not all, putting it on shelf for now until I have a good chunk of free time to figure it out. Cheers!

**Comment by tomverweij** [comment]
Hi @patim 
Solved it!
Not that it may help you but it might help others: when working on Windows, use the WinPython release (https://winpython.github.io/). After a few detours I stumbled on http://stackoverflow.com/questions/14273853/numpy-and-scipy-installation-on-windows which turned out to be most straightforward. Just deinstalled "plain Python2.7", and installed WinPython.
cheers!

**Comment by patim** [comment]
I was able to install the packages manually carefully following this post
http://chrisstrelioff.ws/sandbox/2014/06/04/install_and_setup_python_and_packages_on_ubuntu_14_04.html
Hope this helps!
