### ISSUE TITLE
What does "add credentials to twitter_secrets.json.nogit" mean?

### ISSUE THREAD

**Issue by gsganden** [thedataincubator/ds30#7]
Should we create a new text file called twitter_secrets.json.nogit? If so, then how should that file be formatted? If not, then what should we do instead?

**Comment by tianhuil** [comment]
Hi @gsganden: thanks for asking.  Why don't you try reading the readme first.

**Comment by gsganden** [comment]
I did. It says "add those credentials to `twitter_secrets.json.nogit` (this file is intentionally ignored by git)." I don't know what that means.

**Comment by gsganden** [comment]
Now I see the formatting guidelines. Am I supposed to do this in a new file that I create?
