### ISSUE TITLE
Notebook does not appear to be JSON

### ISSUE THREAD

**Issue by 2mariya** [thedataincubator/ds30#8]
Hi! I have the following message in my IPython Notebook when I choose DS30.ipynb. 

Error loading notebook
Unreadable Notebook: C:\Python34\Scripts\DataIncubatorWebinar\DS30.ipynb NotJSONError('Notebook does not appear to be JSON: \'\n\n\n<!DOCTYPE html>\n<html lang="en" ...',)

**Comment by tianhuil** [comment]
@2mariya: it looks like the notebook you are trying to open is in HTML.  Try checking the code out using `git` rather than downloading it from the web-rendered view.
